name: bound
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - numpy
  - cfgrib  # meteo data
  - matplotlib # debugging with plots
  - xarray  # field operation
  - metpy   # meteo units
  - scipy   # optimize, for the dispersion relation
  - netcdf4 # loading fields
  - pydap>=3.3.0   # data download
  - docopt  # for pydap
  - lxml    # for pydap, via BS4
  - pip
  - pip:
    - -r requirements.txt